coverage:
  status:
    project:
      default:
        informational: true
        # basic
        target: 80%
        threshold: 10% # allowed drop from previous commit
    patch:
      default:
        informational: true
