# Directory under which to store downloads and all results of the pipeline.
# Relative path names are not allowd. `~` can be used for the home directory.
result_dir = "~/data/yellow-taxis_results/data/"

# reject trip times with duration longer than this as outliers (in seconds)
max_duration = 14400  # 4h

# Reject trip distances with duration longer than this as outliers
max_distance = 1000

# window length for rolling average in days
rolling_window = 45

# step size in days that is used when sampling from all per-month
# running averages to generate a single parquet file for all history
rolling_step = 5
